dist: trusty
sudo: required
language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_install:
  - sudo apt-get -qq update

before_script:
  - composer self-update
  - composer install

script: phpunit